#ifndef __PERF_HPP__
#define __PERF_HPP__ 1

#include <cstdint>
#include <cstddef>
#include <array>
#include <string_view>
#include <vector>
#include <ostream>

namespace perf {

// ── Index constants (position in the counter table) ──────────────────────
namespace Idx {
    constexpr size_t CORE_CYCLE                   =  0;
    constexpr size_t CORE_INSTRET                 =  1;
    constexpr size_t CORE_BUSY_CYCLE              =  2;
    constexpr size_t CORE_STALL_CYCLE             =  3;
    constexpr size_t INST_CLASS_ALU_COUNT         =  4;
    constexpr size_t INST_CLASS_LOAD_COUNT        =  5;
    constexpr size_t INST_CLASS_STORE_COUNT       =  6;
    constexpr size_t INST_CLASS_BRANCH_COUNT      =  7;
    constexpr size_t INST_CLASS_JAL_COUNT         =  8;
    constexpr size_t INST_CLASS_JALR_COUNT        =  9;
    constexpr size_t INST_CLASS_CSR_COUNT         = 10;
    constexpr size_t INST_CLASS_MULDIV_COUNT      = 11;
    constexpr size_t STATE_FETCH_CYCLE            = 12;
    constexpr size_t STATE_DECODE_CYCLE           = 13;
    constexpr size_t STATE_EXECUTE_CYCLE          = 14;
    constexpr size_t STATE_MEMORY_CYCLE           = 15;
    constexpr size_t STATE_WRITEBACK_CYCLE        = 16;
    constexpr size_t STALL_IFETCH_WAIT_RESP_CYCLE = 17;
    constexpr size_t STALL_MEM_WAIT_RESP_CYCLE    = 18;
    constexpr size_t STALL_MEM_REQ_BLOCKED_CYCLE  = 19;
    constexpr size_t STALL_STRUCT_SHARED_MEM_CYCLE= 20;
    constexpr size_t STALL_MULDIV_BUSY_CYCLE      = 21;
    constexpr size_t MEM_LOAD_REQ_COUNT           = 22;
    constexpr size_t MEM_STORE_REQ_COUNT          = 23;
    constexpr size_t MEM_MMIO_REQ_COUNT           = 24;
    constexpr size_t TRAP_EXCEPTION_COUNT         = 25;
} // namespace Idx

// ── Single-source-of-truth counter definition ────────────────────────────

struct PerfCounterDef {
    const char *name;         // e.g. "core.cycle"
    const char *unit;         // e.g. "cycle", "count"
    const char *definition;   // human-readable description
    const char *rawSource;    // DPI signal that drives this counter
};

// ── Lightweight read-only view for TUI / snapshot consumption ────────────

struct PerfCounterView {
    std::string_view name;
    std::string_view unit;
    std::string_view definition;
    uint64_t          value;
};

// ── Accumulator — owns the counter storage ──────────────────────────────

class PerfCounters {
public:
    static constexpr size_t kNumCounters = 26;

    void clear();

    void accumulateCore(uint64_t running, uint64_t commitFire,
                        uint64_t busy, uint64_t stall);
    void accumulateInstClass(uint64_t alu, uint64_t load, uint64_t store,
                             uint64_t branch, uint64_t jal, uint64_t jalr,
                             uint64_t csr, uint64_t muldiv);
    void accumulateState(uint64_t fetch, uint64_t decode, uint64_t execute,
                         uint64_t memory, uint64_t writeback);
    void accumulateStall(uint64_t ifetchWaitResp, uint64_t memWaitResp,
                         uint64_t memReqBlocked, uint64_t structSharedMem,
                         uint64_t muldivBusy);
    void accumulateMem(uint64_t loadReqFire, uint64_t storeReqFire,
                       uint64_t mmioReqFire);
    void accumulateTrap(uint64_t exceptionFire);

    // Direct indexed access (for dump / derived metric computation)
    uint64_t get(size_t idx) const { return m_values[idx]; }

    // Build a full snapshot view for TUI consumption
    std::vector<PerfCounterView> view() const;

private:
    std::array<uint64_t, kNumCounters> m_values{};
};

// ── PerfMonitor — lifecycle + polling entry point ──────────────────────

class PerfMonitor {
public:
    static constexpr size_t kNumCounters = PerfCounters::kNumCounters;

    /// Clear accumulators before a reset; enter reset-gate state.
    void onResetBegin();

    /// Exit reset-gate state; counters are already zeroed.
    void onResetEnd();

    /// Poll RTL perf signals once per stable clock cycle.
    ///
    /// Template parameter DPIModule must expose the 26 public `perf_*`
    /// members generated by Verilator from the `GeneralDPIAdapter`.
    template <typename DPIModule>
    void sampleCycle(const DPIModule *dpi) {
        if (m_resetting) return;
        accumulateCore(
            dpi->perf_core_running,
            dpi->perf_core_commitFire,
            dpi->perf_core_busy,
            dpi->perf_core_stall);
        accumulateInstClass(
            dpi->perf_inst_alu,
            dpi->perf_inst_load,
            dpi->perf_inst_store,
            dpi->perf_inst_branch,
            dpi->perf_inst_jal,
            dpi->perf_inst_jalr,
            dpi->perf_inst_csr,
            dpi->perf_inst_muldiv);
        accumulateState(
            dpi->perf_state_fetch_cycle,
            dpi->perf_state_decode_cycle,
            dpi->perf_state_execute_cycle,
            dpi->perf_state_memory_cycle,
            dpi->perf_state_writeback_cycle);
        accumulateStall(
            dpi->perf_stall_ifetch_wait_resp,
            dpi->perf_stall_mem_wait_resp,
            dpi->perf_stall_mem_req_blocked,
            dpi->perf_stall_structural_shared_mem,
            dpi->perf_stall_muldiv_busy);
        accumulateMem(
            dpi->perf_mem_load_req_fire,
            dpi->perf_mem_store_req_fire,
            dpi->perf_mem_mmio_req_fire);
        accumulateTrap(dpi->perf_trap_exception_fire);
    }

    /// Return a read-only snapshot of all 26 counters.
    std::vector<PerfCounterView> view() const { return m_counters.view(); }

    /// Raw counter access (for derived metric computation).
    const PerfCounters &counters() const { return m_counters; }
    uint64_t get(size_t idx) const { return m_counters.get(idx); }

    /// Get the counter definition at a given index.
    static const PerfCounterDef &counterDef(size_t idx);

    /// Print a summary of all counters to an output stream.
    void dumpSummary(std::ostream &os) const;

    /// Write cycles, instret, ipc, and every perf counter as JSON.
    /// Returns true on success; fails closed on any I/O or formatting error.
    bool dumpJson(const std::string &path) const;

private:
    void accumulateCore(uint64_t running, uint64_t commitFire,
                        uint64_t busy, uint64_t stall) {
        m_counters.accumulateCore(running, commitFire, busy, stall);
    }
    void accumulateInstClass(uint64_t alu, uint64_t load, uint64_t store,
                             uint64_t branch, uint64_t jal, uint64_t jalr,
                             uint64_t csr, uint64_t muldiv) {
        m_counters.accumulateInstClass(alu, load, store, branch, jal, jalr, csr, muldiv);
    }
    void accumulateState(uint64_t fetch, uint64_t decode, uint64_t execute,
                         uint64_t memory, uint64_t writeback) {
        m_counters.accumulateState(fetch, decode, execute, memory, writeback);
    }
    void accumulateStall(uint64_t ifetchWaitResp, uint64_t memWaitResp,
                         uint64_t memReqBlocked, uint64_t structSharedMem,
                         uint64_t muldivBusy) {
        m_counters.accumulateStall(ifetchWaitResp, memWaitResp, memReqBlocked,
                                   structSharedMem, muldivBusy);
    }
    void accumulateMem(uint64_t loadReqFire, uint64_t storeReqFire,
                       uint64_t mmioReqFire) {
        m_counters.accumulateMem(loadReqFire, storeReqFire, mmioReqFire);
    }
    void accumulateTrap(uint64_t exceptionFire) {
        m_counters.accumulateTrap(exceptionFire);
    }

    PerfCounters m_counters;
    bool         m_resetting{false};
};

/// Global singleton — instantiated at static-init time, lives for the
/// entire simulation process.
extern PerfMonitor g_perfMonitor;

} // namespace perf

#endif /* __PERF_HPP__ */
