AM_SRCS := riscv/npc/start.S \
           riscv/npc/trm.c \
           riscv/npc/ioe.c \
           riscv/npc/timer.c \
           riscv/npc/input.c \
           riscv/npc/gpu.c \
           riscv/npc/cte.c \
           riscv/npc/trap.S \
           platform/dummy/vme.c \
           platform/dummy/mpe.c

CFLAGS    += -fdata-sections -ffunction-sections
LDSCRIPTS += $(AM_HOME)/scripts/linker.ld
LDFLAGS   += --defsym=_pmem_start=0x80000000 --defsym=_entry_offset=0x0
LDFLAGS   += --defsym=_pmem_end=0x88000000
LDFLAGS   += --gc-sections -e _start

MAINARGS_MAX_LEN = 64
MAINARGS_PLACEHOLDER = the_insert-arg_rule_in_Makefile_will_insert_mainargs_here
CFLAGS += -DMAINARGS_MAX_LEN=$(MAINARGS_MAX_LEN) -DMAINARGS_PLACEHOLDER=$(MAINARGS_PLACEHOLDER)

insert-arg: image
	@python $(AM_HOME)/tools/insert-arg.py $(IMAGE).bin $(MAINARGS_MAX_LEN) $(MAINARGS_PLACEHOLDER) "$(mainargs)"

image: image-dep
	$(DUMP_ELF)
	@echo + OBJCOPY "->" $(IMAGE_REL).bin
	@$(OBJCOPY) -S --set-section-flags .bss=alloc,contents -O binary $(IMAGE).elf $(IMAGE).bin

CONFIG_SDB_ENABLED ?= false
CONFIG_ITRACE ?= on
CONFIG_MTRACE ?= on
CONFIG_FTRACE ?= on
CONFIG_DTRACE ?= on
CONFIG_ETRACE ?= on
CONFIG_TRACE_FORMAT ?= both
CONFIG_TRACE_DATA_MODE ?= stores
CONFIG_DIFFTEST ?= off
CONFIG_DEVICE ?= off
CONFIG_NVBOARD ?= off
CONFIG_VGA ?= off
CONFIG_WAVE ?= off
CONFIG_TUI ?= off
CONFIG_DEBUG_OUTPUT ?= off
CONFIG_MROM ?= off
CONFIG_DIFFTEST_PORT ?= 12345
CONFIG_TUI_CONFIG_FILE_PATH ?= build/npc-tui.toml
CONFIG_TUI_GENERATE_CONFIG ?= off
CONFIG_TUI_GENERATE_FULL_CONFIG ?= off
CONFIG_TUI_FORCE_OVERWRITE_CONFIG ?= off
CONFIG_TUI_PRINT_CONFIG_SCHEMA ?= off
CONFIG_TUI_PRINT_DEFAULT_CONFIG ?= off
CONFIG_PERF ?= off
CONFIG_PERF_CHECK_STRICT ?= off
CONFIG_FLASH_BIN_FILE_PATH ?= $(IMAGE).bin
CONFIG_FLASH_ELF_FILE_PATH ?= $(IMAGE).elf
CONFIG_MROM_BIN_FILE_PATH ?= mrom.bin
CONFIG_MROM_ELF_FILE_PATH ?= mrom.elf
CONFIG_DIFFTEST_SO_FILE_PATH ?= $(NEMU_HOME)/build/riscv32-nemu-interpreter-so
CONFIG_DIFFTEST_START_MODE ?= reset
CONFIG_DIFFTEST_START_PC ?= 0
CONFIG_DIFFTEST_PAYLOAD_BIN_FILE_PATH ?=
CONFIG_DIFFTEST_PAYLOAD_LOAD_ADDR ?= 0x80000000
CONFIG_DIFFTEST_MEM_MODE ?= auto

TRACE_LOG_DIR = $(abspath ./build/trace-logs)

RUN_ARGS = RUN_SDB_ENABLED=$(CONFIG_SDB_ENABLED) \
	RUN_CONFIG_SIM_MODE=standalone \
	RUN_CONFIG_ITRACE=$(CONFIG_ITRACE) \
	RUN_CONFIG_MTRACE=$(CONFIG_MTRACE) \
	RUN_CONFIG_FTRACE=$(CONFIG_FTRACE) \
	RUN_CONFIG_DTRACE=$(CONFIG_DTRACE) \
	RUN_CONFIG_ETRACE=$(CONFIG_ETRACE) \
	RUN_CONFIG_TRACE_FORMAT=$(CONFIG_TRACE_FORMAT) \
	RUN_CONFIG_TRACE_DATA_MODE=$(CONFIG_TRACE_DATA_MODE) \
	RUN_CONFIG_DIFFTEST=$(CONFIG_DIFFTEST) \
	RUN_CONFIG_DEVICE=$(CONFIG_DEVICE) \
	RUN_CONFIG_NVBOARD=$(CONFIG_NVBOARD) \
	RUN_CONFIG_VGA=$(CONFIG_VGA) \
	RUN_CONFIG_MROM=$(CONFIG_MROM) \
	RUN_CONFIG_WAVE=$(CONFIG_WAVE) \
	RUN_CONFIG_TUI=$(CONFIG_TUI) \
	RUN_CONFIG_DEBUG_OUTPUT=$(CONFIG_DEBUG_OUTPUT) \
	RUN_CONFIG_TUI_CONFIG_FILE_PATH=$(abspath $(CONFIG_TUI_CONFIG_FILE_PATH)) \
	RUN_CONFIG_TUI_GENERATE_CONFIG=$(CONFIG_TUI_GENERATE_CONFIG) \
	RUN_CONFIG_TUI_GENERATE_FULL_CONFIG=$(CONFIG_TUI_GENERATE_FULL_CONFIG) \
	RUN_CONFIG_TUI_FORCE_OVERWRITE_CONFIG=$(CONFIG_TUI_FORCE_OVERWRITE_CONFIG) \
	RUN_CONFIG_TUI_PRINT_CONFIG_SCHEMA=$(CONFIG_TUI_PRINT_CONFIG_SCHEMA) \
	RUN_CONFIG_TUI_PRINT_DEFAULT_CONFIG=$(CONFIG_TUI_PRINT_DEFAULT_CONFIG) \
	RUN_CONFIG_PERF=$(CONFIG_PERF) \
	RUN_CONFIG_PERF_CHECK_STRICT=$(CONFIG_PERF_CHECK_STRICT) \
	RUN_CONFIG_DIFFTEST_PORT=$(CONFIG_DIFFTEST_PORT) \
	RUN_CONFIG_FLASH_BIN_FILE_PATH=$(abspath $(CONFIG_FLASH_BIN_FILE_PATH)) \
	RUN_CONFIG_FLASH_ELF_FILE_PATH=$(abspath $(CONFIG_FLASH_ELF_FILE_PATH)) \
	RUN_CONFIG_MROM_BIN_FILE_PATH=$(abspath $(CONFIG_MROM_BIN_FILE_PATH)) \
	RUN_CONFIG_MROM_ELF_FILE_PATH=$(abspath $(CONFIG_MROM_ELF_FILE_PATH)) \
	RUN_CONFIG_DIFFTEST_SO_FILE_PATH=$(abspath $(CONFIG_DIFFTEST_SO_FILE_PATH)) \
	RUN_CONFIG_DIFFTEST_START_MODE=$(CONFIG_DIFFTEST_START_MODE) \
	RUN_CONFIG_DIFFTEST_START_PC=$(CONFIG_DIFFTEST_START_PC) \
	RUN_CONFIG_DIFFTEST_PAYLOAD_BIN_FILE_PATH=$(CONFIG_DIFFTEST_PAYLOAD_BIN_FILE_PATH) \
	RUN_CONFIG_DIFFTEST_PAYLOAD_LOAD_ADDR=$(CONFIG_DIFFTEST_PAYLOAD_LOAD_ADDR) \
	RUN_CONFIG_DIFFTEST_MEM_MODE=$(CONFIG_DIFFTEST_MEM_MODE) \
	RUN_CONFIG_ITRACE_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/itrace.log) \
	RUN_CONFIG_ITRACE_JSONL_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/itrace.jsonl) \
	RUN_CONFIG_MTRACE_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/mtrace.log) \
	RUN_CONFIG_MTRACE_JSONL_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/mtrace.jsonl) \
	RUN_CONFIG_FTRACE_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/ftrace.log) \
	RUN_CONFIG_DTRACE_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/dtrace.log) \
	RUN_CONFIG_DTRACE_JSONL_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/dtrace.jsonl) \
	RUN_CONFIG_ETRACE_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/etrace.log) \
	RUN_CONFIG_ETRACE_JSONL_OUT_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/etrace.jsonl) \
	RUN_CONFIG_WAVE_FILE_PATH=$(abspath $(TRACE_LOG_DIR)/sim.fst)

run: insert-arg
	echo "Beginning simulation..."
	/bin/sh -c "if [ ! -d $(TRACE_LOG_DIR) ]; then mkdir -p $(TRACE_LOG_DIR); fi"
	$(MAKE) -C $(NPC_HOME) run \
	IMG=$(abspath $(IMAGE).bin) \
	$(RUN_ARGS)

gdb: insert-arg
	echo "Beginning simulation..."
	/bin/sh -c "if [ ! -d $(TRACE_LOG_DIR) ]; then mkdir -p $(TRACE_LOG_DIR); fi"
	$(MAKE) -C $(NPC_HOME) gdb \
	IMG=$(abspath $(IMAGE).bin) \
	$(RUN_ARGS)

.PHONY: insert-arg
