// Synthesis stub for GeneralDPIAdapter — replaces DPI-C calls with zero outputs.
// The original module contains `import "DPI-C"` function calls that are
// unsynthesisable. This stub provides an identical port interface with all
// outputs tied to 0 and all inputs left unconnected (optimised away by Yosys).
//
// Generated from: npc/vsrc/generated/GeneralDPIAdapter.sv
// Do not edit manually — regenerated when Chisel RTL changes.

module GeneralDPIAdapter (
    input         clock,
    input         reset,
    input  [31:0] core_pc,
    input         core_halt,
    input         core_executing,
    input         core_ifuInputValid,
    input         clint_read_readEnable,
    input  [31:0] clint_read_readAddress,
    output [31:0] clint_read_readData,
    input         clint_write_writeEnable,
    input  [31:0] clint_write_writeAddress,
    input  [3:0]  clint_write_writeDataStrobe,
    input  [31:0] clint_write_writeData,
    input  [31:0] gpr_gprs_0,
    input  [31:0] gpr_gprs_1,
    input  [31:0] gpr_gprs_2,
    input  [31:0] gpr_gprs_3,
    input  [31:0] gpr_gprs_4,
    input  [31:0] gpr_gprs_5,
    input  [31:0] gpr_gprs_6,
    input  [31:0] gpr_gprs_7,
    input  [31:0] gpr_gprs_8,
    input  [31:0] gpr_gprs_9,
    input  [31:0] gpr_gprs_10,
    input  [31:0] gpr_gprs_11,
    input  [31:0] gpr_gprs_12,
    input  [31:0] gpr_gprs_13,
    input  [31:0] gpr_gprs_14,
    input  [31:0] gpr_gprs_15,
    input  [31:0] gpr_gprs_16,
    input  [31:0] gpr_gprs_17,
    input  [31:0] gpr_gprs_18,
    input  [31:0] gpr_gprs_19,
    input  [31:0] gpr_gprs_20,
    input  [31:0] gpr_gprs_21,
    input  [31:0] gpr_gprs_22,
    input  [31:0] gpr_gprs_23,
    input  [31:0] gpr_gprs_24,
    input  [31:0] gpr_gprs_25,
    input  [31:0] gpr_gprs_26,
    input  [31:0] gpr_gprs_27,
    input  [31:0] gpr_gprs_28,
    input  [31:0] gpr_gprs_29,
    input  [31:0] gpr_gprs_30,
    input  [31:0] gpr_gprs_31,
    input  [31:0] csr_csr_mstatus,
    input  [31:0] csr_csr_mtvec,
    input  [31:0] csr_csr_mepc,
    input  [31:0] csr_csr_mcause,
    input  [31:0] csr_csr_mtval,
    input  [31:0] csr_csr_mvendorid,
    input  [31:0] csr_csr_marchid,
    input         ifu_if_nextStage_valid,
    input  [31:0] ifu_instData,
    input  [31:0] idu_inst,
    input         idu_id_nextStage_valid,
    input         exu_ecallEnable,
    input         exu_epcRecoverEnable,
    input  [31:0] exu_exPc,
    input         exu_ex_nextStage_valid,
    input         memu_memWriteEnable,
    input         memu_memReadEnable,
    input  [31:0] memu_memAddr,
    input  [31:0] memu_memData,
    input  [3:0]  memu_memStrobe,
    input  [1:0]  memu_memResp,
    input  [3:0]  memu_memLsType,
    input  [31:0] memu_memPc,
    input         memu_mem_nextStage_valid,
    input  [31:0] wbu_pc,
    input  [31:0] wbu_pcNext,
    input  [31:0] wbu_inst,
    input  [4:0]  wbu_rs1,
    input  [4:0]  wbu_rd,
    input  [31:0] wbu_imm,
    input  [31:0] wbu_rs1Data,
    input         wbu_inst_jal,
    input         wbu_inst_jalr,
    input         wbu_wb_nextStage_valid,
    input         perf_core_running,
    input         perf_core_commitFire,
    input         perf_core_busy,
    input         perf_core_stall,
    input         perf_inst_alu,
    input         perf_inst_load,
    input         perf_inst_store,
    input         perf_inst_branch,
    input         perf_inst_jal,
    input         perf_inst_jalr,
    input         perf_inst_csr,
    input         perf_inst_muldiv,
    input         perf_state_fetch_cycle,
    input         perf_state_decode_cycle,
    input         perf_state_execute_cycle,
    input         perf_state_memory_cycle,
    input         perf_state_writeback_cycle,
    input         perf_stall_ifetch_wait_resp,
    input         perf_stall_mem_wait_resp,
    input         perf_stall_mem_req_blocked,
    input         perf_stall_structural_shared_mem,
    input         perf_stall_muldiv_busy,
    input         perf_mem_load_req_fire,
    input         perf_mem_store_req_fire,
    input         perf_mem_mmio_req_fire,
    input         perf_trap_exception_fire
);

  // The only output in the original module: drive to 0 for synthesis.
  // (Original DPI calls may drive this to non-zero values during simulation,
  // but synthesis cannot model DPI behaviour, so 0 is the safe reset value.)
  assign clint_read_readData = 32'h0;

endmodule
