#!/usr/bin/env python3
"""iSTA coverage batch runner — endpoint batching to characterize SIGSEGV crash.

Reads the generated endpoint list from the existing coverage-query pin file,
splits endpoints into batches at increasing sizes, generates per-batch Tcl
scripts, runs iEDA against each batch, and records success/failure in JSON.

The crash bug: iSTA SIGSEGV at 0x0 (null-pointer dereference) during
StaReport.cc when `report_timing -to <ALL endpoints> -nworst 1` writes
out timing reports for a large set of endpoints.  Batching at smaller
sizes isolates the threshold at which the crash triggers.

Evidence: The existing `coverage_query/sta.log` shows:
  - Timing update completes (2101 MB, 0.26 s)
  - Report: 218 paths for core_clock, then 218 more, then 1 more
  - THEN: SIGSEGV (@0x0) from PID 0 during StaReport writer

Usage:
  python3 ista_coverage_batch_runner.py --work-dir NPC_HOME/build/synth [--dry-run]
  python3 ista_coverage_batch_runner.py --work-dir NPC_HOME/build/synth --run --batch-sizes 16,32,64,128

Options:
  --work-dir      Path to build/synth directory (REQUIRED)
  --dry-run       Generate Tcl scripts only; do not invoke iEDA (default)
  --run           Actually invoke iEDA for each batch
  --batch-sizes   Comma-separated list of batch sizes (default: 16,32,64,128,256,512,1024,2048)
  --netlist       Path to .netlist.v (default: auto-detect from canonical_flat)
  --sdc           Path to .sdc (default: auto-detect)
  --ieda-bin      Path to iEDA binary
  --output-json   Path to write batch results JSON
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ── constants ────────────────────────────────────────────────────────
DEFAULT_BATCH_SIZES = [16, 32, 64, 128, 256, 512, 1024, 2048]
REPRO_SUBDIR = "ista_coverage_crash_reproducer"
BATCHES_SUBDIR = "batches"
RESULT_FILE = "coverage_batch_results.json"
DESIGN_NAME = "ysyx_25070190"
FREQ_DIR = f"{DESIGN_NAME}-100MHz"


# ── endpoint extraction ──────────────────────────────────────────────

def extract_endpoints_from_pin_file(pin_file: Path) -> List[str]:
    """Extract the sorted endpoint list from a sta_coverage_pins.tcl file."""
    content = pin_file.read_text(encoding="utf-8", errors="replace")
    # Find `set all_coverage_endpoints { ... }` and extract inside braces
    m = re.search(r"set\s+all_coverage_endpoints\s*\{([^}]*)\}", content)
    if not m:
        raise ValueError(f"No endpoint list found in {pin_file}")
    raw = m.group(1).strip()
    # Split on whitespace
    endpoints = raw.split()
    # Filter empty entries
    endpoints = [e for e in endpoints if e]
    return endpoints


def find_coverage_pin_file(work_dir: Path) -> Optional[Path]:
    """Search for the coverage pin file under canonical_flat or hierarchy_attribution."""
    candidates = [
        work_dir / "canonical_flat" / FREQ_DIR / "coverage_query" / "sta_coverage_pins.tcl",
        work_dir / "hierarchy_attribution" / FREQ_DIR / "coverage_query" / "sta_coverage_pins.tcl",
    ]
    for c in candidates:
        if c.is_file():
            return c
    return None


def auto_detect_paths(work_dir: Path) -> Tuple[Path, Path, Path]:
    """Auto-detect netlist, SDC, and iEDA paths relative to work_dir (build/synth)."""
    base = work_dir / "canonical_flat" / FREQ_DIR
    netlist = base / f"{DESIGN_NAME}.netlist.v"
    sdc = base / "abc.sdc"
    # iEDA binary is under yosys-sta/bin/ relative to NPC root
    yosys_sta = work_dir.parent.parent / "yosys-sta"
    ieda = yosys_sta / "bin" / "iEDA"
    return netlist, sdc, ieda


# ── Tcl generation ───────────────────────────────────────────────────

def generate_single_batch_tcl(
    batch_id: int,
    batch_size: int,
    endpoints: List[str],
    netlist_path: Path,
    sdc_path: Path,
    yosys_sta_home: Path,
    output_dir: Path,
) -> Path:
    """Generate a Tcl script for one batch of endpoints."""
    design = DESIGN_NAME
    pdk = "nangate45"

    batch_eps = endpoints  # the caller already sliced

    # Build the pin list
    pin_list_str = " ".join(batch_eps)

    tcl_content = f"""\
# Auto-generated by ista_coverage_batch_runner.py — batch {batch_id} (size={batch_size})
# Endpoints in this batch: {len(batch_eps)}

set SDC_FILE         [lindex $argv 0]
set NETLIST_V        [lindex $argv 1]
set DESIGN           [lindex $argv 2]
set PDK              [lindex $argv 3]
set YOSYS_STA_HOME   [lindex $argv 4]

set RESULT_DIR [file dirname $NETLIST_V]
file mkdir $RESULT_DIR

source "$YOSYS_STA_HOME/scripts/common.tcl"

set_design_workspace $RESULT_DIR
read_netlist $NETLIST_V
read_liberty [concat $LIB_FILES]
link_design $DESIGN
read_sdc $SDC_FILE

set batch_endpoints {{{pin_list_str}}}

# Coverage query for this batch: target {len(batch_eps)} endpoints
report_timing -to $batch_endpoints \\
  -delay_type max -nworst 1 -max_path {len(batch_eps) + 100} -json

exit
"""
    tcl_path = output_dir / f"batch_{batch_id:03d}_size_{batch_size:04d}.tcl"
    tcl_path.write_text(tcl_content)
    return tcl_path


def generate_all_batch_tcls(
    all_endpoints: List[str],
    batch_sizes: List[int],
    netlist_path: Path,
    sdc_path: Path,
    yosys_sta_home: Path,
    output_dir: Path,
) -> List[Dict]:
    """Generate Tcl scripts for all batch sizes. Returns batch metadata list."""
    batches_meta = []
    total = len(all_endpoints)

    for bs in batch_sizes:
        # Split endpoints into batches of `bs`
        batch_idx = 0
        for start in range(0, total, bs):
            batch_endpoints = all_endpoints[start : start + bs]
            actual_size = len(batch_endpoints)

            tcl_path = generate_single_batch_tcl(
                batch_id=batch_idx,
                batch_size=bs,
                endpoints=batch_endpoints,
                netlist_path=netlist_path,
                sdc_path=sdc_path,
                yosys_sta_home=yosys_sta_home,
                output_dir=output_dir,
            )

            batches_meta.append({
                "batch_group": bs,
                "batch_index": batch_idx,
                "endpoint_count": actual_size,
                "tcl_file": str(tcl_path),
                "endpoints": batch_endpoints,
            })
            batch_idx += 1

    return batches_meta


# ── iEDA invocation ─────────────────────────────────────────────────

def find_libraries() -> Dict[str, str]:
    """Find required shared libraries for iEDA in the Nix store."""
    lib_dirs = {}
    # libunwind
    for p in Path("/nix/store").glob("*libunwind*/lib/libunwind.so.*"):
        lib_dirs.setdefault("libunwind", str(p.parent))
    # libstdc++
    for p in Path("/nix/store").glob("*gcc-*-lib/lib/libstdc++.so.*"):
        lib_dirs.setdefault("libstdcxx", str(p.parent))
    # libgcc_s
    for p in Path("/nix/store").glob("*gcc-*-libgcc/lib/libgcc_s.so.*"):
        lib_dirs.setdefault("libgcc", str(p.parent))
    return lib_dirs


def run_ista_batch(
    tcl_path: Path,
    netlist_path: Path,
    sdc_path: Path,
    ieda_bin: Path,
    yosys_sta_home: Path,
    result_dir: Path,
    timeout_seconds: int = 300,
) -> Dict:
    """Run one iEDA batch query. Returns result dict."""
    design = DESIGN_NAME
    pdk = "nangate45"

    # Assemble LD_LIBRARY_PATH
    libs = find_libraries()
    ld_path_parts = []
    for name in ["libunwind", "libstdcxx", "libgcc"]:
        if name in libs:
            ld_path_parts.append(libs[name])
    ld_path = ":".join(ld_path_parts)

    env = os.environ.copy()
    if ld_path:
        env["LD_LIBRARY_PATH"] = f"{ld_path}:{env.get('LD_LIBRARY_PATH', '')}"

    cmd = [
        str(ieda_bin),
        "-script", str(tcl_path),
        str(sdc_path.resolve()),
        str(netlist_path.resolve()),
        design,
        pdk,
        str(yosys_sta_home),
    ]

    result_dir.mkdir(parents=True, exist_ok=True)

    start_time = time.time()
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            cwd=str(result_dir),
            env=env,
        )
        elapsed = time.time() - start_time

        stdout = proc.stdout or ""
        stderr = proc.stderr or ""

        # Detect crash patterns
        crashed = False
        crash_reason = ""
        if proc.returncode != 0:
            if "SIGSEGV" in stderr or "SIGSEGV" in stdout:
                crashed = True
                crash_reason = "SIGSEGV"
            elif "SIGABRT" in stderr or "SIGABRT" in stdout:
                crashed = True
                crash_reason = "SIGABRT"
            elif proc.returncode == -11:
                crashed = True
                crash_reason = "SIGSEGV (signal 11)"
            elif proc.returncode == -6:
                crashed = True
                crash_reason = "SIGABRT (signal 6)"

        # Write stdout/stderr to files
        (result_dir / "stdout.txt").write_text(stdout)
        (result_dir / "stderr.txt").write_text(stderr)

        # Check if .rpt file was produced
        rpt_file = result_dir / f"{design}.rpt"
        rpt_produced = rpt_file.is_file()

        # Check if summary JSON was produced
        summary_json = result_dir / f"{design}_sta_summary.json"
        json_produced = summary_json.is_file()

        # Parse glog for more crash detail
        glog_path = result_dir / "glog_dump.log"
        crash_trace = ""
        if glog_path.is_file():
            crash_trace = glog_path.read_text(encoding="utf-8", errors="replace")[:2000]

        result = {
            "exit_code": proc.returncode,
            "crashed": crashed,
            "crash_reason": crash_reason,
            "crash_trace": crash_trace[:500] if crash_trace else "",
            "elapsed_seconds": round(elapsed, 3),
            "rpt_produced": rpt_produced,
            "json_produced": json_produced,
            "stdout_snippet": stdout[-500:] if len(stdout) > 500 else stdout,
            "stderr_snippet": stderr[-500:] if len(stderr) > 500 else stderr,
        }

        # Extract timing report counts from stdout/stderr
        report_counts = re.findall(
            r"report the clock group \S+ (\d+) timing paths",
            stdout + stderr,
        )
        if report_counts:
            result["reported_path_counts"] = [int(c) for c in report_counts]

        return result

    except subprocess.TimeoutExpired:
        elapsed = time.time() - start_time
        (result_dir / "stdout.txt").write_text("(timeout)")
        (result_dir / "stderr.txt").write_text("(timeout)")
        return {
            "exit_code": -1,
            "crashed": True,
            "crash_reason": f"TIMEOUT ({timeout_seconds}s)",
            "crash_trace": "",
            "elapsed_seconds": round(elapsed, 3),
            "rpt_produced": False,
            "json_produced": False,
            "stdout_snippet": "",
            "stderr_snippet": "",
        }

    except FileNotFoundError:
        elapsed = time.time() - start_time
        return {
            "exit_code": -2,
            "crashed": False,
            "crash_reason": "iEDA binary not found",
            "crash_trace": "",
            "elapsed_seconds": round(elapsed, 3),
            "rpt_produced": False,
            "json_produced": False,
            "stdout_snippet": "",
            "stderr_snippet": "",
        }


# ── result aggregation ───────────────────────────────────────────────

def collect_batch_results(
    batches_meta: List[Dict],
    run_results: Dict[str, Dict],
    all_endpoints: List[str],
    work_dir: Path,
    coverage_query_status: str,
    existing_log_evidence: Optional[Dict] = None,
) -> Dict:
    """Assemble the final coverage_batch_results.json structure."""
    total_endpoints = len(all_endpoints)

    existing_crash_log = build_existing_crash_log_path(work_dir)

    # Group results by batch size
    by_size: Dict[int, List[Dict]] = {}
    for meta in batches_meta:
        bs = meta["batch_group"]
        by_size.setdefault(bs, [])
        entry = {
            "batch_index": meta["batch_index"],
            "endpoint_count": meta["endpoint_count"],
            "tcl_file": meta["tcl_file"],
        }
        tcl_key = meta["tcl_file"]
        if tcl_key in run_results:
            entry["result"] = run_results[tcl_key]
        by_size[bs].append(entry)

    # Find the smallest crashing batch size
    crash_sizes = []
    for bs, entries in by_size.items():
        all_crashed = all(
            e.get("result", {}).get("crashed", False) for e in entries
        )
        any_crashed = any(
            e.get("result", {}).get("crashed", False) for e in entries
        )
        if all_crashed or any_crashed:
            crash_sizes.append(bs)

    smallest_crash = min(crash_sizes) if crash_sizes else None

    # Check if batching fully avoids crash
    all_success = all(
        not e.get("result", {}).get("crashed", False)
        for entries in by_size.values()
        for e in entries
    )

    if coverage_query_status.startswith("dry_run"):
        verdict = "ISTA_DEFECT_DOCUMENTED__BATCH_INFRA_READY"
    elif all_success:
        verdict = "FULL_COVERAGE_BY_BATCHING"
    else:
        verdict = "ISTA_DEFECT_DOCUMENTED"

    result = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "metadata": {
            "total_endpoints": total_endpoints,
            "batch_sizes_tested": sorted(by_size.keys()),
            "num_batches_total": sum(len(v) for v in by_size.values()),
            "coverage_query_status": coverage_query_status,
        },
        "existing_crash_evidence": {
            "location": str(existing_crash_log),
            "log_present": existing_log_evidence.get("existing_log_present", False) if existing_log_evidence else False,
            "sigsegv_confirmed": existing_log_evidence.get("sigsegv_confirmed", False) if existing_log_evidence else False,
            "crash_at_pc_zero": existing_log_evidence.get("crash_at_pc_zero", False) if existing_log_evidence else False,
            "crash_type": "SIGSEGV (@0x0) from PID 0",
            "crash_phase": "StaReport write",
            "context": (
                "iSTA loads design, builds timing graph, starts writing "
                "timing reports, reports 218+218+1 paths for core_clock, "
                "then crashes with null-pointer dereference during report "
                "write. Crash is at PC 0x0 in StaReport.cc."
            ),
        },
        "binary_status": {
            "ieda_binary": str(batches_meta[0].get("ieda_bin", "N/A")) if batches_meta else "N/A",
            "ieda_version": "see existing_crash_evidence or re-run with --run",
            "is_functional": False,
            "note": (
                "Current iEDA binary (git 071226fa) crashes during design "
                "loading (SIGSEGV before timing analysis).  The successful "
                "canonical STA and the crash-evidence coverage query were "
                "run with a previous binary (git aa25008b).  The batch "
                "infrastructure is ready; re-run with --run when iEDA is "
                "updated to a functional version."
            ),
        },
        "batches_by_size": {
            str(bs): {
                "size": bs,
                "num_batches": len(entries),
                "all_crashed": all(
                    e.get("result", {}).get("crashed", False) for e in entries
                ),
                "any_crashed": any(
                    e.get("result", {}).get("crashed", False) for e in entries
                ),
                "batches": entries,
            }
            for bs, entries in by_size.items()
        },
        "outcome": {
            "full_coverage_achieved": all_success and not coverage_query_status.startswith("dry_run"),
            "smallest_crashing_batch_size": smallest_crash,
            "verdict": verdict,
            "reproduction_ready": True,
        },
    }

    return result


def build_existing_crash_log_path(work_dir: Path) -> Path:
    """Build path to the existing crash log from canonical_flat."""
    return (
        work_dir / "canonical_flat" / FREQ_DIR
        / "coverage_query" / "glog_dump.log"
    )


# ── dry-run mode ────────────────────────────────────────────────────

def dry_run_batch_runner(
    all_endpoints: List[str],
    batch_sizes: List[int],
    netlist_path: Path,
    sdc_path: Path,
    yosys_sta_home: Path,
    batches_dir: Path,
    work_dir: Path,
) -> Dict:
    """Generate Tcl scripts but do not run iEDA."""
    batches_dir.mkdir(parents=True, exist_ok=True)

    batches_meta = generate_all_batch_tcls(
        all_endpoints=all_endpoints,
        batch_sizes=batch_sizes,
        netlist_path=netlist_path,
        sdc_path=sdc_path,
        yosys_sta_home=yosys_sta_home,
        output_dir=batches_dir,
    )

    # No run results in dry-run
    run_results = {}

    # Check if the existing crash log is present and parse it for evidence
    crash_log_path = build_existing_crash_log_path(work_dir)
    evidence_from_log = {}
    if crash_log_path.is_file():
        log_text = crash_log_path.read_text(encoding="utf-8", errors="replace")
        evidence_from_log["existing_log_present"] = True
        evidence_from_log["sigsegv_confirmed"] = "SIGSEGV" in log_text
        evidence_from_log["crash_at_pc_zero"] = " @                0x0" in log_text
    else:
        evidence_from_log["existing_log_present"] = False

    return collect_batch_results(
        batches_meta=batches_meta,
        run_results=run_results,
        all_endpoints=all_endpoints,
        work_dir=work_dir,
        coverage_query_status="dry_run_tcls_generated",
        existing_log_evidence=evidence_from_log,
    )


# ── real run mode ───────────────────────────────────────────────────

def run_batch_runner(
    all_endpoints: List[str],
    batch_sizes: List[int],
    netlist_path: Path,
    sdc_path: Path,
    yosys_sta_home: Path,
    ieda_bin: Path,
    batches_dir: Path,
    work_dir: Path,
) -> Dict:
    """Run iEDA for every batch and record results."""
    batches_dir.mkdir(parents=True, exist_ok=True)

    batches_meta = generate_all_batch_tcls(
        all_endpoints=all_endpoints,
        batch_sizes=batch_sizes,
        netlist_path=netlist_path,
        sdc_path=sdc_path,
        yosys_sta_home=yosys_sta_home,
        output_dir=batches_dir,
    )

    # Inject ieda_bin into metadata for JSON
    for m in batches_meta:
        m["ieda_bin"] = str(ieda_bin)

    crash_log_path = build_existing_crash_log_path(work_dir)

    run_results = {}
    for meta in batches_meta:
        tcl_path = Path(meta["tcl_file"])
        result_dir = tcl_path.parent / tcl_path.stem
        result_dir.mkdir(parents=True, exist_ok=True)

        print(f"  Batch {meta['batch_group']}/{meta['batch_index']} "
              f"({meta['endpoint_count']} endpoints)... ", end="", flush=True)

        result = run_ista_batch(
            tcl_path=tcl_path,
            netlist_path=netlist_path,
            sdc_path=sdc_path,
            ieda_bin=ieda_bin,
            yosys_sta_home=yosys_sta_home,
            result_dir=result_dir,
        )

        status = "CRASH" if result["crashed"] else ("OK" if result["exit_code"] == 0 else f"ERR({result['exit_code']})")
        print(f"{status} ({result['elapsed_seconds']:.1f}s)")

        run_results[str(tcl_path)] = result

    return collect_batch_results(
        batches_meta=batches_meta,
        run_results=run_results,
        all_endpoints=all_endpoints,
        work_dir=work_dir,
        coverage_query_status=(
            "iSTA_ran" if any(r.get("exit_code", -1) == 0 for r in run_results.values())
            else "iSTA_crashed_all"
        ),
        existing_log_evidence={"existing_log_present": crash_log_path.is_file()},
    )


# ── main ─────────────────────────────────────────────────────────────

def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="iSTA coverage batch runner — characterize endpoint coverage SIGSEGV"
    )
    parser.add_argument("--work-dir", type=str, required=True,
                        help="Path to build/synth directory")
    parser.add_argument("--dry-run", action="store_true", default=True,
                        help="Generate Tcl scripts only (default)")
    parser.add_argument("--run", dest="dry_run", action="store_false",
                        help="Actually invoke iEDA for each batch")
    parser.add_argument("--batch-sizes", type=str,
                        default="16,32,64,128,256,512,1024,2048",
                        help="Comma-separated batch sizes")
    parser.add_argument("--netlist", type=str, default="",
                        help="Path to .netlist.v")
    parser.add_argument("--sdc", type=str, default="",
                        help="Path to .sdc file")
    parser.add_argument("--ieda-bin", type=str, default="",
                        help="Path to iEDA binary")
    parser.add_argument("--output-json", type=str, default="",
                        help="Path to write results JSON")
    args = parser.parse_args()

    # Resolve work_dir
    work_dir = Path(args.work_dir).resolve()
    if not work_dir.is_dir():
        print(f"ERROR: work-dir does not exist or is not a directory: {work_dir}", file=sys.stderr)
        sys.exit(1)

    # Parse batch sizes
    batch_sizes = [int(x.strip()) for x in args.batch_sizes.split(",") if x.strip()]
    if not batch_sizes:
        batch_sizes = DEFAULT_BATCH_SIZES

    # Paths derived from work_dir
    repro_dir = work_dir / REPRO_SUBDIR
    batches_dir = repro_dir / BATCHES_SUBDIR
    result_json = Path(args.output_json) if args.output_json else work_dir / RESULT_FILE

    # Auto-detect paths
    netlist, sdc, ieda = auto_detect_paths(work_dir)
    if args.netlist:
        netlist = Path(args.netlist)
    if args.sdc:
        sdc = Path(args.sdc)
    if args.ieda_bin:
        ieda = Path(args.ieda_bin)

    yosys_sta_home = ieda.parent.parent

    # Validate paths
    if not netlist.is_file():
        print(f"ERROR: Netlist not found: {netlist}", file=sys.stderr)
        sys.exit(1)
    if not sdc.is_file():
        print(f"ERROR: SDC not found: {sdc}", file=sys.stderr)
        sys.exit(1)

    # Load endpoints
    pin_file = find_coverage_pin_file(work_dir)
    if not pin_file:
        print("ERROR: No coverage pin file found. Run coverage query first.", file=sys.stderr)
        sys.exit(1)

    all_endpoints = extract_endpoints_from_pin_file(pin_file)
    print(f"Work dir: {work_dir}")
    print(f"Loaded {len(all_endpoints)} endpoints from {pin_file}")
    print(f"Batch sizes: {batch_sizes}")
    print(f"Netlist: {netlist}")
    print(f"SDC: {sdc}")

    # Run
    if args.dry_run:
        print("\n--- DRY RUN: Generating Tcl scripts ---")
        results = dry_run_batch_runner(
            all_endpoints, batch_sizes, netlist, sdc, yosys_sta_home,
            batches_dir=batches_dir,
            work_dir=work_dir,
        )
    else:
        print("\n--- RUNNING iEDA batches ---")
        results = run_batch_runner(
            all_endpoints, batch_sizes, netlist, sdc, yosys_sta_home, ieda,
            batches_dir=batches_dir,
            work_dir=work_dir,
        )

    # Write JSON
    result_json.parent.mkdir(parents=True, exist_ok=True)

    json_text = json.dumps(results, indent=2, default=str)
    result_json.write_text(json_text)
    print(f"\nResults written to {result_json}")

    # Summary
    outcome = results["outcome"]
    meta = results["metadata"]
    print(f"\nSummary:")
    print(f"  Total endpoints: {meta['total_endpoints']}")
    print(f"  Batches total: {meta['num_batches_total']}")
    print(f"  Sizes tested: {meta['batch_sizes_tested']}")
    print(f"  Verdict: {outcome['verdict']}")
    if outcome.get("smallest_crashing_batch_size"):
        print(f"  Smallest crashing batch: {outcome['smallest_crashing_batch_size']}")

    # Print crash evidence summary
    ev = results.get("existing_crash_evidence", {})
    if ev:
        print(f"\nExisting crash evidence:")
        print(f"  Location: {ev.get('location', 'N/A')}")
        print(f"  Type: {ev.get('crash_type', 'N/A')}")
        print(f"  Phase: {ev.get('crash_phase', 'N/A')}")


if __name__ == "__main__":
    main()
